/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PassengerService } from "../passenger.service";
import { PassengerCreateInput } from "./PassengerCreateInput";
import { Passenger } from "./Passenger";
import { PassengerFindManyArgs } from "./PassengerFindManyArgs";
import { PassengerWhereUniqueInput } from "./PassengerWhereUniqueInput";
import { PassengerUpdateInput } from "./PassengerUpdateInput";
import { ReservationFindManyArgs } from "../../reservation/base/ReservationFindManyArgs";
import { Reservation } from "../../reservation/base/Reservation";
import { ReservationWhereUniqueInput } from "../../reservation/base/ReservationWhereUniqueInput";

export class PassengerControllerBase {
  constructor(protected readonly service: PassengerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Passenger })
  async createPassenger(
    @common.Body() data: PassengerCreateInput
  ): Promise<Passenger> {
    return await this.service.createPassenger({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Passenger] })
  @ApiNestedQuery(PassengerFindManyArgs)
  async passengers(@common.Req() request: Request): Promise<Passenger[]> {
    const args = plainToClass(PassengerFindManyArgs, request.query);
    return this.service.passengers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async passenger(
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<Passenger | null> {
    const result = await this.service.passenger({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePassenger(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() data: PassengerUpdateInput
  ): Promise<Passenger | null> {
    try {
      return await this.service.updatePassenger({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Passenger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePassenger(
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<Passenger | null> {
    try {
      return await this.service.deletePassenger({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/reservations")
  @ApiNestedQuery(ReservationFindManyArgs)
  async findReservations(
    @common.Req() request: Request,
    @common.Param() params: PassengerWhereUniqueInput
  ): Promise<Reservation[]> {
    const query = plainToClass(ReservationFindManyArgs, request.query);
    const results = await this.service.findReservations(params.id, {
      ...query,
      select: {
        bus: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        passenger: {
          select: {
            id: true,
          },
        },

        reservationDate: true,
        seatNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reservations")
  async connectReservations(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        connect: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reservations")
  async updateReservations(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        set: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reservations")
  async disconnectReservations(
    @common.Param() params: PassengerWhereUniqueInput,
    @common.Body() body: ReservationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reservations: {
        disconnect: body,
      },
    };
    await this.service.updatePassenger({
      where: params,
      data,
      select: { id: true },
    });
  }
}
